/**
 * Electron Main Process
 *
 * Entry point for the Electron main process. Handles:
 * - Window creation and management
 * - Python subprocess initialization
 * - IPC handlers for Python communication
 */

// Suppress GLib-GObject warnings on Linux (harmless GTK threading noise in Electron)
if (process.platform === 'linux') {
  process.env.GDK_BACKEND = process.env.GDK_BACKEND || 'x11';
}

import log from 'electron-log/main';
Object.assign(console, log.functions);

import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { getErrorMessage } from '../utils/errors';
import { PythonProcess } from './python-process';
import { ScanCoordinator } from './scan-coordinator';
import { CameraProcess } from './camera-process';
import type { CameraSettings } from './camera-process';
import { DEFAULT_CAMERA_SETTINGS } from '../types/camera';
import { DAQProcess } from './daq-process';

import { ScannerProcess } from './scanner-process';
import type { ScannerSettings } from '../types/scanner';
import {
  getPythonExecutablePath,
  validatePythonExecutable,
} from './python-paths';
import { initializeDatabase, closeDatabase, getDatabase } from './database';
import { registerDatabaseHandlers } from './database-handlers';
import {
  registerGraviscanHandlers,
  autoInitScanners,
} from './graviscan-handlers';
import { scanLog, cleanupOldLogs, closeScanLog } from './scan-logger';
import {
  loadEnvConfig,
  saveEnvConfig,
  validateConfig,
  fetchScannersFromBloom,
  MachineConfig,
} from './config-store';
import {
  getSessionState,
  setSessionState,
  resetSessionState,
  type SessionState,
} from './session-store';

// Config file paths
const BLOOM_DIR = path.join(os.homedir(), '.bloom');
const ENV_PATH = path.join(BLOOM_DIR, '.env');

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Enable remote debugging for E2E tests specifically
// This must be set before app.ready event fires
// Playwright requires remote debugging to control the app
// Uses E2E_TEST flag (from .env.e2e) instead of broad CI flag to avoid enabling for all CI builds
//
// NOTE (Nov 2025): The primary fix for the --remote-debugging-port=0 "bad option" error is in
// playwright.config.ts (deletes ELECTRON_RUN_AS_NODE env var). This app.commandLine.appendSwitch
// is kept as defense-in-depth but may no longer be strictly required.
// See: docs/E2E_TESTING.md (Pitfall 6) for full explanation of the root cause.
if (process.env.E2E_TEST === 'true') {
  // Use app.commandLine.appendSwitch() to set debugging flags via Electron's internal API
  app.commandLine.appendSwitch('remote-debugging-port', '0'); // 0 = any free port
  console.log('[E2E] Remote debugging enabled for E2E test environment');
}

// Configuration constants
const STOP_STREAM_TIMEOUT_MS = 2000; // Timeout for stopping camera stream during quit

let mainWindow: BrowserWindow | null = null;
let pythonProcess: PythonProcess | null = null;
let scanCoordinator: ScanCoordinator | null = null;

// Scan session state — tracks active scan progress so the renderer can
// restore state when remounting (e.g. user navigates away and back).
interface ScanSessionJob {
  scannerId: string;
  plateIndex: string;
  outputPath: string;
  plantBarcode: string | null;
  gridMode: string;
  status: 'pending' | 'scanning' | 'complete' | 'error';
  imagePath?: string;
  error?: string;
  durationMs?: number;
  cycleNumber?: number;
  dbRecorded?: boolean;
}

interface ScanSessionState {
  isActive: boolean;
  isContinuous: boolean; // true for interval/continuous scanning
  experimentId: string;
  phenotyperId: string;
  resolution: number;
  sessionId: string | null; // GraviScanSession DB record ID
  jobs: Record<string, ScanSessionJob>; // key: scannerId:plateIndex
  // Continuous scan timing (persisted across tab navigation)
  currentCycle: number;
  totalCycles: number;
  intervalMs: number;
  scanStartedAt: number | null; // epoch ms
  scanDurationMs: number;
  coordinatorState: 'idle' | 'scanning' | 'waiting';
  nextScanAt: number | null; // epoch ms when next cycle starts
  waveNumber: number;
}

let scanSession: ScanSessionState | null = null;

export function getScanSession(): ScanSessionState | null {
  return scanSession;
}

export function setScanSession(session: ScanSessionState | null): void {
  scanSession = session;
}

export function markScanJobRecorded(jobKey: string): void {
  if (scanSession?.jobs[jobKey]) {
    scanSession.jobs[jobKey].dbRecorded = true;
  }
}
let cameraProcess: CameraProcess | null = null;
const daqProcess: DAQProcess | null = null;
let scannerProcess: ScannerProcess | null = null;

// Track current camera settings (in-memory, lost on app restart)
let currentCameraSettings: CameraSettings | null = null;

/**
 * Scanner identity (runtime state)
 *
 * Holds the current scanner name, initialized from .env at startup
 * and synced when config is saved. Provides fast in-memory access
 * for UI components without file I/O.
 *
 * Pattern matches currentCameraSettings (ephemeral runtime state).
 * Pilot reference: bloom-desktop-pilot/app/src/main/main.ts:148
 */
const scannerIdentity: { name: string } = { name: '' };

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      // TODO: Replace webSecurity: false with a custom protocol handler for file:// URLs
      // This is needed to load local scan images from HTTP context (webpack-dev-server)
      // Reference: pilot implementation uses same approach
      // See: https://github.com/Salk-Harnessing-Plants-Initiative/bloom-desktop/issues/93
      webSecurity: false,
    },
  });

  mainWindow.menuBarVisible = false;
  mainWindow.setMenu(null);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

/**
 * Initialize Python subprocess and set up event handlers
 */
async function initializePythonProcess(): Promise<void> {
  try {
    // Validate Python executable exists
    validatePythonExecutable();

    // Get Python executable path
    const pythonPath = getPythonExecutablePath();

    // Create Python process instance
    pythonProcess = new PythonProcess(pythonPath, ['--ipc']);

    // Forward Python status events to renderer
    pythonProcess.on('status', (status: string) => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('python:status', status);
      }
    });

    // Forward Python errors to renderer
    pythonProcess.on('error', (error: string) => {
      console.error('Python error:', error);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('python:error', error);
      }
    });

    // Handle Python process exit
    pythonProcess.on('exit', (code: number | null) => {
      console.log(`Python process exited with code ${code}`);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('python:status', `Process exited: ${code}`);
      }
    });

    // Start the Python process
    await pythonProcess.start();
    console.log('Python process started successfully');
  } catch (error) {
    console.error('Failed to initialize Python process:', error);
    // Send error to renderer if window exists
    if (mainWindow) {
      mainWindow.webContents.send(
        'python:error',
        `Failed to start Python: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }
}

/**
 * Initialize the ScanCoordinator for per-scanner subprocess management.
 * The coordinator is created here but subprocesses are spawned on-demand
 * when the user starts a scan via the start-scan IPC handler.
 */
function initializeScanCoordinator(): void {
  // Clean up old coordinator listeners to prevent accumulation on re-init
  if (scanCoordinator) {
    scanCoordinator.removeAllListeners();
  }

  const mockEnabled = process.env.GRAVISCAN_MOCK?.toLowerCase() === 'true';

  try {
    // In production: use bundled bloom-hardware with --scan-worker flag
    // In development: use .venv Python with -m graviscan.scan_worker
    let pythonPath: string;
    if (app.isPackaged) {
      pythonPath = getPythonExecutablePath();
    } else {
      const venvPython = path.join(process.cwd(), '.venv', 'bin', 'python');
      pythonPath = fs.existsSync(venvPython) ? venvPython : 'python3';
    }

    scanCoordinator = new ScanCoordinator(
      pythonPath,
      app.isPackaged,
      mockEnabled
    );

    // Log scan events to persistent file + forward to renderer + update session state
    scanCoordinator.on('scan-event', (event) => {
      // Persistent file logging
      switch (event.type) {
        case 'scan-started':
          scanLog(`[${event.scanner_id}] Scanning plate ${event.plate_index}`);
          break;
        case 'scan-complete':
          scanLog(
            `[${event.scanner_id}] Plate ${event.plate_index} complete (${event.duration_ms}ms) → ${event.path}`
          );
          break;
        case 'scan-error':
          scanLog(
            `[${event.scanner_id}] Plate ${event.plate_index} ERROR: ${event.error}`
          );
          break;
        case 'scan-cancelled':
          scanLog(`[${event.scanner_id}] Plate ${event.plate_index} cancelled`);
          break;
      }

      // Update session state (persists across renderer unmount/remount)
      if (scanSession?.isActive) {
        const jobKey = `${event.scanner_id}:${event.plate_index}`;
        const job = scanSession.jobs[jobKey];
        if (job) {
          switch (event.type) {
            case 'scan-started':
              job.status = 'scanning';
              scanSession.coordinatorState = 'scanning';
              scanSession.nextScanAt = null;
              break;
            case 'scan-complete':
              job.status = 'complete';
              job.imagePath = event.path;
              job.durationMs = event.duration_ms;
              job.cycleNumber = event.cycle_number;
              break;
            case 'scan-error':
              job.status = 'error';
              job.error = event.error;
              break;
            case 'scan-cancelled':
              job.status = 'error';
              job.error = 'Cancelled';
              break;
          }
        }

        // Check if all jobs are done → deactivate session (single mode only).
        // In continuous mode, jobs repeat each cycle, so session stays active
        // until interval-complete fires.
        if (
          !scanSession.isContinuous &&
          (event.type === 'scan-complete' ||
            event.type === 'scan-error' ||
            event.type === 'scan-cancelled')
        ) {
          const allDone = Object.values(scanSession.jobs).every(
            (j) => j.status === 'complete' || j.status === 'error'
          );
          if (allDone) {
            console.log(
              '[ScanSession] All jobs finished, deactivating session'
            );
            scanSession.isActive = false;

            // Update session completed_at timestamp
            if (scanSession.sessionId) {
              const db = getDatabase();
              db.graviScanSession
                .update({
                  where: { id: scanSession.sessionId },
                  data: { completed_at: new Date() },
                })
                .catch((err: unknown) =>
                  console.error(
                    '[ScanSession] Failed to update session completed_at:',
                    err
                  )
                );
            }
          }
        }
      }

      if (!mainWindow || mainWindow.isDestroyed()) return;

      switch (event.type) {
        case 'scan-started':
          mainWindow.webContents.send('graviscan:scan-started', {
            jobId: event.job_id,
            scannerId: event.scanner_id,
            plateIndex: event.plate_index,
          });
          break;
        case 'scan-complete':
          mainWindow.webContents.send('graviscan:scan-complete', {
            jobId: event.job_id,
            scannerId: event.scanner_id,
            plateIndex: event.plate_index,
            imagePath: event.path,
            durationMs: event.duration_ms,
            cycleNumber: event.cycle_number,
            scanStartedAt: event.scan_started_at || null,
          });
          break;
        case 'scan-error':
          mainWindow.webContents.send('graviscan:scan-error', {
            jobId: event.job_id,
            scannerId: event.scanner_id,
            plateIndex: event.plate_index,
            error: event.error,
          });
          break;
        case 'scan-cancelled':
          mainWindow.webContents.send('graviscan:scan-cancelled', {
            jobId: event.job_id,
            scannerId: event.scanner_id,
            plateIndex: event.plate_index,
          });
          break;
        case 'cycle-done':
          mainWindow.webContents.send('graviscan:cycle-done', {
            scannerId: event.scanner_id,
            cycle: event.cycle,
          });
          break;
      }
    });

    // Forward grid-level events (per-grid timestamps for DB records)
    scanCoordinator.on('grid-complete', (data) => {
      scanLog(
        `Grid ${data.gridIndex} complete: st=${data.scanStartedAt} et=${data.scanEndedAt}`
      );

      // Update session job imagePaths to reflect renamed files (adds _et_ timestamp)
      // Without this, downstream consumers (QR verification, file browser) get stale paths
      // Note: don't check isActive — grid-complete fires after session deactivates for row 2
      if (scanSession && data.renamedFiles) {
        for (const rf of data.renamedFiles) {
          const jobKey = `${rf.scannerId}:${data.gridIndex}`;
          const job = scanSession.jobs[jobKey];
          if (job && job.imagePath === rf.oldPath) {
            job.imagePath = rf.newPath;
            scanLog(`Updated job path: ${jobKey} → ${rf.newPath}`);
          }
        }
      }

      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:grid-complete', {
          cycle: data.cycle,
          gridIndex: data.gridIndex,
          scanStartedAt: data.scanStartedAt,
          scanEndedAt: data.scanEndedAt,
          renamedFiles: data.renamedFiles || [],
        });
      }
    });

    // Log and forward interval-level events
    scanCoordinator.on('interval-start', (data) => {
      scanLog(
        `Continuous scan started: ${data.totalCycles} cycles, ${data.intervalMs}ms interval, ${data.durationMs}ms duration`
      );
      // Persist timing to session state
      if (scanSession) {
        scanSession.totalCycles = data.totalCycles;
        scanSession.intervalMs = data.intervalMs;
        scanSession.scanDurationMs = data.durationMs;
        scanSession.scanStartedAt = data.startedAt;
        scanSession.coordinatorState = 'scanning';
      }
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:interval-start', {
          totalCycles: data.totalCycles,
          intervalMs: data.intervalMs,
          durationMs: data.durationMs,
          startedAt: data.startedAt,
        });
      }
    });

    scanCoordinator.on('cycle-complete', (data) => {
      scanLog(`Cycle ${data.cycle} complete`);
      // Update session timing
      if (scanSession) {
        scanSession.currentCycle = data.cycle;
        scanSession.coordinatorState = 'idle'; // briefly idle between cycle-complete and interval-waiting
      }
      // In continuous mode, reset job statuses for the next cycle
      if (scanSession?.isActive && scanSession.isContinuous) {
        for (const job of Object.values(scanSession.jobs)) {
          job.status = 'pending';
        }
      }
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:cycle-complete', data);
      }
    });

    scanCoordinator.on('interval-waiting', (data) => {
      scanLog(`Waiting ${data.nextScanMs}ms for next cycle`);
      // Update session timing
      if (scanSession) {
        scanSession.coordinatorState = 'waiting';
        scanSession.nextScanAt = Date.now() + data.nextScanMs;
        scanSession.currentCycle = data.cycle;
        scanSession.totalCycles = data.totalCycles;
      }
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:interval-waiting', data);
      }
    });

    scanCoordinator.on('overtime', (data) => {
      scanLog(
        `Overtime: cycle ${data.cycle}/${data.totalCycles}, +${data.overtimeMs}ms beyond duration`
      );
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:overtime', data);
      }
    });

    scanCoordinator.on('interval-complete', (data) => {
      scanLog(
        `Scan session complete: ${data.cyclesCompleted}/${data.totalCycles} cycles (cancelled=${data.cancelled}, overtimeMs=${data.overtimeMs})`
      );
      // Deactivate continuous session when all cycles are done
      if (scanSession?.isActive && scanSession.isContinuous) {
        console.log(
          '[ScanSession] Continuous scan complete, deactivating session'
        );
        scanSession.isActive = false;

        // Update session completed_at timestamp
        if (scanSession.sessionId) {
          const db = getDatabase();
          db.graviScanSession
            .update({
              where: { id: scanSession.sessionId },
              data: { completed_at: new Date(), cancelled: data.cancelled },
            })
            .catch((err: unknown) =>
              console.error(
                '[ScanSession] Failed to update session completed_at:',
                err
              )
            );
        }
      }
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('graviscan:interval-complete', data);
      }
    });

    console.log(
      '[GraviScan] ScanCoordinator initialized (mock:',
      mockEnabled,
      ')'
    );
  } catch (error) {
    console.error('[GraviScan] Failed to initialize ScanCoordinator:', error);
  }
}

/**
 * Get the current ScanCoordinator instance (used by IPC handlers).
 */
export function getScanCoordinator(): ScanCoordinator | null {
  return scanCoordinator;
}

// =============================================================================
// IPC Handlers for Python Communication
// =============================================================================

/**
 * Handle python:send-command - Send arbitrary command to Python
 */
ipcMain.handle('python:send-command', async (_event, command: object) => {
  try {
    if (!pythonProcess || !pythonProcess.isRunning()) {
      throw new Error('Python process not running');
    }
    const response = await pythonProcess.sendCommand(command);
    return { success: true, data: response };
  } catch (error: unknown) {
    console.error('python:send-command error:', error);
    return { success: false, error: getErrorMessage(error) };
  }
});

/**
 * Handle python:get-version - Get Python backend version
 */
ipcMain.handle('python:get-version', async () => {
  try {
    if (!pythonProcess || !pythonProcess.isRunning()) {
      throw new Error('Python process not running');
    }
    const response = await pythonProcess.sendCommand({
      command: 'get_version',
    });
    return response;
  } catch (error: unknown) {
    console.error('python:get-version error:', error);
    throw error;
  }
});

/**
 * Handle python:check-hardware - Check hardware availability
 */
ipcMain.handle('python:check-hardware', async () => {
  try {
    if (!pythonProcess || !pythonProcess.isRunning()) {
      throw new Error('Python process not running');
    }
    const response = await pythonProcess.sendCommand({
      command: 'check_hardware',
    });
    return response;
  } catch (error: unknown) {
    console.error('python:check-hardware error:', error);
    throw error;
  }
});

/**
 * Handle python:restart - Restart Python subprocess
 */
ipcMain.handle('python:restart', async () => {
  try {
    if (pythonProcess) {
      await pythonProcess.restart();
      return { success: true };
    } else {
      // If no process exists, try to initialize
      await initializePythonProcess();
      return { success: true };
    }
  } catch (error: unknown) {
    console.error('python:restart error:', error);
    return { success: false, error: getErrorMessage(error) };
  }
});

// =============================================================================
// IPC Handlers for Camera Communication
// =============================================================================

/**
 * Initialize camera subprocess if not already initialized
 */
async function ensureCameraProcess(): Promise<CameraProcess> {
  if (!cameraProcess) {
    const pythonPath = getPythonExecutablePath();
    cameraProcess = new CameraProcess(pythonPath, ['--ipc']);

    // Forward camera events to renderer
    cameraProcess.on('camera-trigger', () => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('camera:trigger');
      }
    });

    cameraProcess.on('image-captured', (dataUri: string) => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('camera:image-captured', {
          dataUri,
          timestamp: Date.now(),
        });
      }
    });

    cameraProcess.on('frame', (dataUri: string) => {
      // Check if window still exists and hasn't been destroyed
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('camera:frame', {
          dataUri,
          timestamp: Date.now(),
        });
      }
    });

    cameraProcess.on('status', (status: string) => {
      console.log('Camera status:', status);
    });

    cameraProcess.on('error', (error: string) => {
      console.error('Camera error:', error);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('camera:error', error);
      }
    });

    cameraProcess.on('exit', (code: number | null) => {
      console.log(`Camera process exited with code ${code}`);
      cameraProcess = null;
    });

    await cameraProcess.start();
  }

  return cameraProcess;
}

/**
 * Handle camera:configure - Configure camera settings
 */
ipcMain.handle(
  'camera:configure',
  async (_event, settings: Partial<CameraSettings>) => {
    try {
      console.log('[camera:configure] Configuring with settings:', settings);
      const camera = await ensureCameraProcess();
      const success = await camera.configure(settings);

      // Store settings in memory if successfully configured
      if (success) {
        currentCameraSettings = {
          ...(currentCameraSettings || DEFAULT_CAMERA_SETTINGS),
          ...settings,
        } as CameraSettings;
        console.log(
          '[camera:configure] Stored settings:',
          currentCameraSettings
        );
      } else {
        console.log('[camera:configure] Failed to configure, not storing');
      }

      return { success };
    } catch (error: unknown) {
      console.error('camera:configure error:', error);
      return { success: false, error: getErrorMessage(error) };
    }
  }
);

/**
 * Handle camera:get-status - Get camera status
 */
ipcMain.handle('camera:get-status', async () => {
  try {
    if (!cameraProcess) {
      return { connected: false, mock: true, available: false };
    }
    const status = await cameraProcess.getStatus();
    return status;
  } catch (error: unknown) {
    console.error('camera:get-status error:', error);
    return { connected: false, mock: true, available: false };
  }
});

/**
 * Handle camera:get-settings - Get current camera settings
 */
ipcMain.handle('camera:get-settings', async () => {
  console.log(
    '[camera:get-settings] Returning settings:',
    currentCameraSettings
  );
  return currentCameraSettings;
});

/**
 * Handle camera:start-stream - Start streaming frames from camera
 */
ipcMain.handle(
  'camera:start-stream',
  async (_event, settings?: Partial<CameraSettings>) => {
    try {
      const camera = await ensureCameraProcess();
      const success = await camera.startStream(settings);
      return { success };
    } catch (error: unknown) {
      console.error('camera:start-stream error:', error);
      return { success: false, error: getErrorMessage(error) };
    }
  }
);

/**
 * Handle camera:stop-stream - Stop streaming frames from camera
 */
ipcMain.handle('camera:stop-stream', async () => {
  try {
    if (!cameraProcess) {
      return { success: true }; // Already stopped
    }
    const success = await cameraProcess.stopStream();
    return { success };
  } catch (error: unknown) {
    console.error('camera:stop-stream error:', error);
    return { success: false, error: getErrorMessage(error) };
  }
});

// =============================================================================
// IPC Handlers for DAQ Communication
// =============================================================================

// =============================================================================
// IPC Handlers for Scanner Communication
// =============================================================================

/**
 * Initialize Scanner subprocess if not already initialized
 */
async function ensureScannerProcess(): Promise<ScannerProcess> {
  if (!scannerProcess) {
    // Scanner uses the same Python process as other hardware
    if (!pythonProcess) {
      throw new Error('Python process not initialized');
    }

    scannerProcess = new ScannerProcess(pythonProcess);

    // Forward scanner events to renderer
    scannerProcess.on('initialized', () => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('scanner:initialized');
      }
    });

    scannerProcess.on('progress', (progress) => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('scanner:progress', progress);
      }
    });

    scannerProcess.on('complete', (result) => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('scanner:complete', result);
      }
    });

    scannerProcess.on('error', (error: string) => {
      console.error('Scanner error:', error);
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('scanner:error', error);
      }
    });
  }

  return scannerProcess;
}

/**
 * Handle scanner:initialize - Initialize scanner with camera and DAQ settings
 */
ipcMain.handle(
  'scanner:initialize',
  async (_event, settings: ScannerSettings) => {
    try {
      const scanner = await ensureScannerProcess();
      const response = await scanner.initialize(settings);
      return response;
    } catch (error: unknown) {
      console.error('scanner:initialize error:', error);
      return {
        success: false,
        initialized: false,
        error: getErrorMessage(error),
      };
    }
  }
);

/**
 * Handle scanner:scan - Perform a complete scan
 */
ipcMain.handle('scanner:scan', async () => {
  try {
    if (!scannerProcess) {
      throw new Error('Scanner not initialized. Call initialize() first.');
    }
    const response = await scannerProcess.scan();
    return response;
  } catch (error: unknown) {
    console.error('scanner:scan error:', error);
    return {
      success: false,
      frames_captured: 0,
      output_path: '',
      error: getErrorMessage(error),
    };
  }
});

/**
 * Handle scanner:get-scanner-id - Get current scanner identity
 *
 * Returns the scanner's configured name from runtime state.
 * Matches pilot API: scanner.getScannerId()
 *
 * @returns {string} Scanner name or empty string if not configured
 */
ipcMain.handle('scanner:get-scanner-id', (): string => {
  return scannerIdentity.name;
});

// =============================================================================
// IPC Handlers for Configuration
// =============================================================================

/**
 * Handle config:get - Get current configuration and credentials
 * Returns config values with password masked for security
 */
ipcMain.handle('config:get', async () => {
  try {
    // Load unified config from .env
    const config = loadEnvConfig(ENV_PATH);
    const hasCredentials = config.bloom_scanner_password !== '';

    // Return unified config with masked password
    return {
      config: {
        scanner_name: config.scanner_name,
        camera_ip_address: config.camera_ip_address,
        scans_dir: config.scans_dir,
        bloom_api_url: config.bloom_api_url,
        bloom_scanner_username: config.bloom_scanner_username,
        bloom_scanner_password: hasCredentials ? '********' : '',
        bloom_anon_key: config.bloom_anon_key,
        graviscan_system_name: config.graviscan_system_name,
      },
      hasCredentials,
    };
  } catch (error) {
    console.error('config:get error:', error);
    throw error;
  }
});

/**
 * Handle config:set - Save unified configuration
 * Validates config before saving
 */
ipcMain.handle('config:set', async (_event, config: MachineConfig) => {
  try {
    // Validate config (validateConfig needs to be updated to handle credential fields)
    const validation = validateConfig(config);
    if (!validation.valid) {
      return { success: false, errors: validation.errors };
    }

    // Save unified config to .env
    saveEnvConfig(config, ENV_PATH);

    // Sync scanner identity from saved config
    scannerIdentity.name = config.scanner_name || '';
    console.log('[Scanner Identity] Updated:', scannerIdentity.name);

    return { success: true };
  } catch (error) {
    console.error('config:set error:', error);
    return {
      success: false,
      errors: {
        general:
          error instanceof Error ? error.message : 'Unknown error occurred',
      },
    };
  }
});

/**
 * Handle config:test-camera - Test connection to camera at given IP
 */
ipcMain.handle('config:test-camera', async (_event, ipAddress: string) => {
  try {
    // For 'mock' camera, always succeed
    if (ipAddress === 'mock') {
      return { success: true };
    }

    // Try to connect to the camera using CameraProcess
    const camera = await ensureCameraProcess();
    const connectResult = await camera.connect({
      ...DEFAULT_CAMERA_SETTINGS,
      camera_ip_address: ipAddress,
    });

    if (connectResult) {
      // Disconnect after successful test
      await camera.disconnect();
      return { success: true };
    } else {
      return {
        success: false,
        error: `Failed to connect to camera at ${ipAddress}`,
      };
    }
  } catch (error) {
    console.error('config:test-camera error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
});

/**
 * Handle config:browse-directory - Open native folder picker dialog
 */
ipcMain.handle('config:browse-directory', async () => {
  try {
    if (!mainWindow) {
      return null;
    }

    const result = await dialog.showOpenDialog(mainWindow, {
      properties: ['openDirectory', 'createDirectory'],
      title: 'Select Scans Directory',
    });

    if (result.canceled || result.filePaths.length === 0) {
      return null;
    }

    return result.filePaths[0];
  } catch (error) {
    console.error('config:browse-directory error:', error);
    return null;
  }
});

/**
 * Handle config:exists - Check if configuration file exists
 * Used for first-run detection
 */
ipcMain.handle('config:exists', async () => {
  try {
    // Check if .env file exists (unified config)
    return fs.existsSync(ENV_PATH);
  } catch (error) {
    console.error('config:exists error:', error);
    return false;
  }
});

/**
 * Handle config:fetch-scanners - Fetch valid scanners from Bloom API
 * Updated to accept parameters (apiUrl and credentials) from form
 */
ipcMain.handle(
  'config:fetch-scanners',
  async (
    _event,
    apiUrl: string,
    credentials: {
      bloom_scanner_username: string;
      bloom_scanner_password: string;
      bloom_anon_key: string;
    }
  ) => {
    try {
      // Validate parameters
      if (
        !apiUrl ||
        !credentials.bloom_scanner_username ||
        !credentials.bloom_scanner_password ||
        !credentials.bloom_anon_key
      ) {
        return {
          success: false,
          error: 'Bloom API URL and credentials are required',
        };
      }

      const result = await fetchScannersFromBloom(apiUrl, credentials);

      return result;
    } catch (error) {
      console.error('config:fetch-scanners error:', error);
      return {
        success: false,
        error:
          error instanceof Error ? error.message : 'Failed to fetch scanners',
      };
    }
  }
);

// =============================================================================
// Session State Handlers
// =============================================================================

/**
 * Handle session:get - Get current session state
 */
ipcMain.handle('session:get', async (): Promise<SessionState> => {
  return getSessionState();
});

/**
 * Handle session:set - Update session state (partial update)
 */
ipcMain.handle(
  'session:set',
  async (_event, updates: Partial<SessionState>): Promise<SessionState> => {
    setSessionState(updates);
    return getSessionState();
  }
);

/**
 * Handle session:reset - Reset session state to initial values
 */
ipcMain.handle('session:reset', async (): Promise<void> => {
  resetSessionState();
});

// =============================================================================
// App Lifecycle
// =============================================================================

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  // Clean up old scan log files (>30 days)
  cleanupOldLogs();

  // Initialize database and register handlers BEFORE creating window
  // so IPC handlers are ready when the renderer loads
  try {
    console.log('[Main] Initializing database...');
    await initializeDatabase();
    console.log('[Main] Database initialized, registering handlers...');
    registerDatabaseHandlers();
    console.log('[Main] Database initialized and handlers registered');

    // Register GraviScan handlers early (before Python init) so renderer can call them
    // Pass null for pythonProcess initially - it will be updated after Python starts
    const db = getDatabase();
    registerGraviscanHandlers(
      db,
      () => mainWindow,
      () => scanCoordinator
    );
    console.log(
      '[Main] GraviScan handlers registered (awaiting Python process)'
    );
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error('[Main] Failed to initialize database:', errorMessage);
  }

  createWindow();

  // Send database ready message to renderer after window is created
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('database:ready', { success: true });
  }

  await initializePythonProcess();

  // Initialize the ScanCoordinator (per-scanner subprocess management)
  initializeScanCoordinator();
  console.log('[Main] ScanCoordinator initialized');

  // Initialize scanner identity from config
  try {
    const config = loadEnvConfig(ENV_PATH);
    scannerIdentity.name = config.scanner_name || '';
    if (config.graviscan_system_name) {
      process.env.GRAVISCAN_SYSTEM_NAME = config.graviscan_system_name;
    }
    console.log(
      '[Scanner Identity] Initialized:',
      scannerIdentity.name || '(not configured)'
    );
  } catch (error) {
    console.error('[Scanner Identity] Failed to initialize:', error);
    scannerIdentity.name = '';
  }

  // Auto-initialize scanner subprocesses from DB config (non-blocking)
  const database = getDatabase();
  if (database && scanCoordinator) {
    autoInitScanners(database, scanCoordinator, mainWindow).catch(
      (err: unknown) => console.error('[Main] Scanner auto-init failed:', err)
    );
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Clean up processes before app quits
let isQuitting = false;
app.on('before-quit', async (event) => {
  // Prevent infinite loop - only run cleanup once
  if (isQuitting) {
    return;
  }

  console.log('App is quitting, cleaning up processes...');
  isQuitting = true;

  // Prevent immediate quit to allow cleanup
  event.preventDefault();

  try {
    // Stop camera streaming first with timeout
    if (cameraProcess) {
      console.log('Stopping camera streaming...');
      let stopStreamCompleted = false;
      const stopStreamPromise = cameraProcess.stopStream().then(() => {
        stopStreamCompleted = true;
      });
      await Promise.race([
        stopStreamPromise,
        new Promise((resolve) => setTimeout(resolve, STOP_STREAM_TIMEOUT_MS)),
      ]);
      if (stopStreamCompleted) {
        console.log('Camera stream stopped successfully');
      } else {
        console.warn(
          'Camera stream stop timed out, force-stopping camera process...'
        );
        try {
          cameraProcess.stop();
        } catch (stopErr) {
          console.error('Error force-stopping camera process:', stopErr);
        }
      }
    }

    // Stop all processes
    if (pythonProcess) {
      console.log('Stopping Python process...');
      pythonProcess.stop();
      console.log('Python process stopped');
    }
    if (scanCoordinator) {
      console.log('Shutting down ScanCoordinator...');
      await scanCoordinator.shutdown();
      console.log('ScanCoordinator shutdown complete');
    }
    if (cameraProcess) {
      console.log('Stopping camera process...');
      cameraProcess.stop();
      console.log('Camera process stopped');
    }
    if (daqProcess) {
      console.log('Stopping DAQ process...');
      daqProcess.stop();
      console.log('DAQ process stopped');
    }

    // Close database connection
    console.log('Closing database connection...');
    await closeDatabase();
    console.log('Database connection closed');

    // Give processes a moment to clean up
    console.log('Waiting 500ms for processes to clean up...');
    await new Promise((resolve) => setTimeout(resolve, 500));
    console.log('Cleanup wait complete');
  } catch (err) {
    console.error('Error during cleanup:', err);
  }

  // Now allow the quit - use exit instead of quit to avoid triggering before-quit again
  console.log('Calling app.exit(0)...');
  app.exit(0);
});

// Clean up processes when app quits (fallback)
app.on('quit', () => {
  closeScanLog();
  if (scanCoordinator) {
    scanCoordinator.killAll();
  }
  if (pythonProcess) {
    pythonProcess.stop();
  }
  if (cameraProcess) {
    cameraProcess.stop();
  }
  if (daqProcess) {
    daqProcess.stop();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
